---
title: "Assignment_Three Q2"
author: "Author - Eric Opoku"
date: "December 8, 2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
fontsize: 12pt
geometry: margin=1in
keep_tex: yes
---


```{r setup, include=FALSE, comment=NA}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.width = 8,
	message = FALSE,
	warning = FALSE,
	collapse = TRUE
)
```


```{r header, echo=TRUE, message=FALSE, warning=FALSE, comment=NA}


name<- Sys.info()
name[7]
```



```{r message=FALSE, warning=FALSE, comment=NA}

library(rlang)
library(dplyr)
library(kableExtra)
library(ggdag)      # For plotting DAGs
library(dagitty)    # For working with DAG logic
library(modelsummary) # For making regression tables
library(AER) # this package has lots of applied metrics packages
library(foreign) 
# Helpful for reading in data from Stata or other code languages 
library(lubridate) # For figures
library(stargazer) # For tables
library(data.table)  #data manipulation and wrangling
library(lme4)
library(psych)
library(readxl) # Read in data
library(expss) #value labelling from spss style
library(readstata13)
library(marginaleffects) # To calculate marginal effects
library(knitr) # Alternative table package
library(ggplot2)





######
### 0. Load the packages we will need for this file ####
library(tidyverse) # load the installed package for each new session of R
library(broom)
library(causaldata) # Useful toy data sets
library(here) # Helpful in working with directories and projects
library(zoo) # Helpful packages for organizing dates
library(tidysynth) # For synthetic controls
library(gsynth) # For synthetic controls
library(gghighlight) # For figures 
library(binsreg) # For binscatters
library(nprobust) # Local linear regression

library(fixest)

set.seed(032620) # random number generators; same numbers across machines
```


#QUESTION ONE


```{r message=FALSE, warning=FALSE, comment=NA}
mydata<- read_excel("C:/Users/erico/Desktop/ACADEMICS/MY UofT COURSES/YEAR TWO/SEMESTER ONE/HAD5744H Applied Health Econometrics I/ASSIGNMENTS/ASSIGNMENT 3/a3_p1_sourdough_trends.xlsx") 

#View(mydata)


#regdata$the_date<-mydata$date  # I will use this data later

mydata$date <- as.yearmon(mydata$date)

  
table(mydata$date)
table(mydata$hits)
table(mydata$keyword)
table(mydata$time)
table(mydata$gprop)
table(mydata$category)
table(mydata$geo)


```


#QUESTION ONE A:

```{r Line graph, message=FALSE, warning=FALSE, comment=NA}


# Group to month level
mydata <- mydata %>% group_by(date, keyword) %>% 
  summarize(hits = sum(hits,na.rm=T))
#Show hits over time for each Keyword
ggplot(mydata,aes(x=date,y=hits,group=keyword)) + geom_line() + 
  theme_classic() + labs(x="Time",y="Monthly Hits")+ 
  geom_vline(xintercept = '2020.211',color='red')




```


## QUESTION ONE B:


```{r Prior trends, message=FALSE, warning=FALSE, comment=NA}
table(mydata$keyword)


# Definition of key variables
mydata <- mydata %>% mutate(treated = ifelse(keyword == "sourdough", 1, 0), 
                              interaction = ifelse(keyword == "sourdough",date,0))

# Statistical tests: are the two groups' trends different?
pretrend_test <- lm(hits ~ date + interaction, data=mydata)
msummary(list(pretrend_test),
         vcov=c(rep("robust",1)),
         stars=c('*' = .1, '**' = .05, '***' = .01)) # Interpret each coefficient here
```
## QUESTION ONE C:


```{r Relative month, message=FALSE, warning=FALSE, comment=NA}
# Definition of key variables
mydata <- mydata %>% mutate(the_keyword = ifelse(keyword == "sourdough",1,0))
mydata <- mydata %>% mutate(After = ifelse(date >= "Mar 2020",1,0))
#mydata <- mydata %>% mutate(inter = keyword * post)
                            
table(mydata$hits)
table(mydata$After)
table(mydata$the_keyword)


# transform the data #Run pre trends again?
mydata <- mydata %>% mutate(logy = log(hits))


# First, construct relative time variable
mydata <- mydata %>% mutate(relative_month = round((as.numeric(date) - 2020.211)*12)) 

#View(mydata)




```

#QUESTION ONE D

```{r TWFE, message=FALSE, warning=FALSE, comment=NA}

#difference-in-difference estimate of the effect of lockdown on sourdough popularity.


dte <- feols(logy ~ i(relative_month, the_keyword, ref = -1) | 
                date + keyword, data = mydata)

# And use coefplot() for a graph of effects
iplot(dte,ref.line=-0.2, 
         ref.line.par=list(col="red",lty=1,lwd=2))


```




 


#QUESTION TWO

#A

```{r Synth control, message=FALSE, warning=FALSE, comment=NA}

mydata2<- read_excel("C:/Users/erico/Desktop/ACADEMICS/MY UofT COURSES/YEAR TWO/SEMESTER ONE/HAD5744H Applied Health Econometrics I/ASSIGNMENTS/ASSIGNMENT 3/a3_p2_organ_donations.xlsx") 

#View(mydata2)


```

```{r message=FALSE, warning=FALSE, comment=NA}

summary(mydata2$LivingDonors)

summary(mydata2$AllDonors)


summary(mydata2$WaitinglistAdditions)


```

```{r rates of living organ donations, message=FALSE, warning=FALSE, comment=NA}
#population-adjusted
mydata2$LivingDonors<-mydata2$LivingDonors*mydata2$Population
mydata2$AllDonors<-mydata2$AllDonors*mydata2$Population
mydata2$WaitinglistAdditions<-mydata2$WaitinglistAdditions*mydata2$Population

mydata2$GDP_percapita<-mydata2$GDP/mydata2$Population

#rate of living organ donations
mydata2$rate_LivingDonors<-(mydata2$LivingDonors*mydata2$Population)
#table(mydata2$rate_LivingDonors)



# Some descriptive figures
ggplot(mydata2, aes(x = Year, 
                y = rate_LivingDonors, 
                group = State)) +
  geom_line() + 
  gghighlight(State=="Louisiana",
              label_params = list(fill = NA, alpha=1)) +
  geom_vline(xintercept = lubridate::make_date(2015), linetype = "solid") +
  labs(
    title = "Rates of living organ donations by State by year",
    caption = "Timing of The living organ donations",
    x = "Date",
    y = "Rates of living organ donated"
  ) +
  theme_minimal()



```

#B




#C



#D


```{r Synthetic cont, message=FALSE, warning=FALSE, comment=NA}
mydata2$centered_year<-mydata2$Year-2015
# Construct Synthetic Controls
donation_out <-
  mydata2  %>%
  # initial the synthetic control object
  synthetic_control(outcome = rate_LivingDonors, # outcome
                    unit = State, # unit index in the panel data
                    time = centered_year, # time index in the panel data
                    i_unit = "Louisiana", # unit where the intervention occurred
                    i_time = 0, # time period when the intervention occurred
                    generate_placebos=T # generate placebo synthetic controls (for inference)
  ) %>%
  # Matching on fully vaccinated the weeks before the intervention  
  generate_predictor(time_window = -15, lagged_donations_year15 = rate_LivingDonors) %>%
  generate_predictor(time_window = -14, lagged_donations_year14 = rate_LivingDonors) %>%
  generate_predictor(time_window = -13, lagged_donations_year13 = rate_LivingDonors) %>%
  generate_predictor(time_window = -12, lagged_donations_year12 = rate_LivingDonors) %>%
  generate_predictor(time_window = -11, lagged_donations_year11 = rate_LivingDonors) %>%
  generate_predictor(time_window = -10, lagged_donations_year10 = rate_LivingDonors) %>%
  generate_predictor(time_window = -09, lagged_donations_year09 = rate_LivingDonors) %>%
  generate_predictor(time_window = -08, lagged_donations_year08 = rate_LivingDonors) %>%
  generate_predictor(time_window = -07, lagged_donations_year07 = rate_LivingDonors) %>%
  generate_predictor(time_window = -06, lagged_donations_year06 = rate_LivingDonors) %>%
  generate_predictor(time_window = -05, lagged_donations_year05 = rate_LivingDonors) %>%
  generate_predictor(time_window = -04, lagged_donations_year04 = rate_LivingDonors) %>%
  generate_predictor(time_window = -03, lagged_donations_year03 = rate_LivingDonors) %>%
  generate_predictor(time_window = -02, lagged_donations_year02 = rate_LivingDonors) %>%
  generate_predictor(time_window = -01, lagged_donations_year01 = rate_LivingDonors) %>%
  # Generate the fitted weights for the synthetic control
  generate_weights(optimization_window = -15:-1, # time to use in the optimization task
                   margin_ipop = .02,sigf_ipop = 7,bound_ipop = 6 # optimizer options
  ) %>%
  # Generate the synthetic control
  generate_control()





#relative weights

# Which states are we using, and what weights are they given? 
donation_out %>%
  grab_unit_weights() %>%
  mutate(weights = round(weight, digits = 4)) %>%
  select(unit, weights) %>%
  filter(weights>0.0001) %>%
  as.data.frame() %>%
  stargazer(summary = FALSE, rownames = FALSE)

# What about the independent variables?
donation_out %>% 
  plot_weights() + 
  labs(title="Synthetic Control Weights") 
```


#E

```{r Balance table}

# Balance Table
donation_out %>%
  grab_balance_table() %>%
  mutate(difference = Louisiana - synthetic_Louisiana) %>%
  select(variable, Louisiana, synthetic_Louisiana, difference, donor_sample) %>%
  as.data.frame() %>%
  stargazer(summary = FALSE, rownames = FALSE, 
            caption = "Balance Table", 
            label = "balancetable") # Note: try this in R Markdown


donation_out %>% plot_trends() +
  scale_x_continuous(breaks = c(-15,-10,-5,0,5)) +
  labs(
    title = "Louisiana and Synthetic Louisiana",
    caption = "Timing of The donations",
    x="Years Relative to donations",
    y="rate of odnations"
  ) 

```

#F

```{r }

# Plot Model Differences
donation_out %>% plot_differences() +
  scale_x_continuous(breaks = c(-15,-10,-5,0,5)) +
  labs(
   title = "Louisiana and Synthetic Louisiana",
    caption = "Timing of The donations",
    x="Years Relative to donations",
    y="rate of odnations"
  ) 


```


#G


```{r Placebo tests}
#i:
# Plot placebos of different states' assignments
donation_out %>% plot_placebos() +
  scale_x_continuous(breaks = c(-15,-10,-5,0,5)) +
  labs(
    title = "Difference between State and Synthetic State: All States",
    caption = "Timing of The donations",
    x="Years Relative to donations",
    y="difference in the rate of odnations"
  ) 


#ii

# This test shifts the pre-treatment window back five weeks.
# This analysis was included in our pre-registration as a demonstration of the 
# method and to show that we did not find treatment effects before the lottery 
# was announced. 

placebo_out <-
  mydata2 %>% 
  filter(centered_year <= 0) %>% 
  # initial the synthetic control object
  synthetic_control(outcome = rate_LivingDonors, # outcome
                    unit = State, # unit index in the panel data
                    time = centered_year, # time index in the panel data
                    i_unit = "Louisiana", # unit where the intervention occurred
                    i_time = -5, # time period when the intervention occurred
                    generate_placebos=T # generate placebo synthetic controls (for inference)
  ) %>%

  # Matching on fully vaccinated the weeks before the intervention  
  generate_predictor(time_window = -15, lagged_donations_yr15 = rate_LivingDonors) %>%
  generate_predictor(time_window = -14, lagged_donations_yr14 = rate_LivingDonors) %>%
  generate_predictor(time_window = -13, lagged_donations_yr13 = rate_LivingDonors) %>%
  generate_predictor(time_window = -12, lagged_donations_yr12 = rate_LivingDonors) %>%
  generate_predictor(time_window = -11, lagged_donations_yr11 = rate_LivingDonors) %>%
  generate_predictor(time_window = -10, lagged_donations_yr10 = rate_LivingDonors) %>%
  generate_predictor(time_window = -09, lagged_donations_yr09 = rate_LivingDonors) %>%
  generate_predictor(time_window = -08, lagged_donations_yr08 = rate_LivingDonors) %>%
  generate_predictor(time_window = -07, lagged_donations_yr07 = rate_LivingDonors) %>%
  generate_predictor(time_window = -06, lagged_donations_yr06 = rate_LivingDonors) %>%
  generate_predictor(time_window = -05, lagged_donations_yr05 = rate_LivingDonors) %>%
  generate_predictor(time_window = -04, lagged_donations_yr04 = rate_LivingDonors) %>%
  generate_predictor(time_window = -03, lagged_donations_yr03 = rate_LivingDonors) %>%
  generate_predictor(time_window = -02, lagged_donations_yr02 = rate_LivingDonors) %>%
  generate_predictor(time_window = -01, lagged_donations_yr01 = rate_LivingDonors) %>%
  # Generate the fitted weights for the synthetic control
  generate_weights(optimization_window = -15:-1, # time to use in the optimization task
                   margin_ipop = .02,sigf_ipop = 7,bound_ipop = 6 # optimizer options
  ) %>%
  # Generate the synthetic control
  generate_control()



placebo_out %>% plot_trends()  + 
  labs(
    title = "Placebo Analysis: Louisiana and Synthetic Louisiana",
  caption = "Timing of The donations",
    x="Years Relative to donations",
    y="rate of odnations"
  )


placebo_out %>% plot_differences()  + 
  labs(
    title = "Placebo Analysis:  Difference between Ohio and Synthetic Ohio",
   caption = "Timing of The donations",
    x="Years Relative to donations",
    y="rate of odnations"
  )

placebo_out %>% grab_signficance() %>% filter(unit_name=="OH")
placebo_out %>% grab_unit_weights() %>% arrange(desc(weight))

placebo_out %>% plot_mspe_ratio() 

```


#H




```{r References,  echo=TRUE, message=FALSE, comment=NA, results='asis'}
packages <- knitr::write_bib(file = 'packages.bib')
packages

```